// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Process = require("process");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

var app = Express.express(/* () */0);

function onListen($$event) {
  var val;
  try {
    val = $$event;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  console.log("Listening on http//localhost: " + (String(8008) + ""));
  return /* () */0;
}

var server = Express.App.listen(app, 8008, undefined, onListen, /* () */0);

var port = 8008;

exports.app = app;
exports.port = port;
exports.onListen = onListen;
exports.server = server;
/* app Not a pure module */
